### ISSUE TITLE
redmine_git_hosting seems not to work with redmine (master https://github.com/redmine/redmine.git #259a394)

### ISSUE THREAD

**Issue by tomhub** [redmine-git-hosting/redmine_git_hosting#831]
When running puma (`bundle exec puma -e production -w 2`) I get these errors (after few moments):
```
[1133] ! Unable to start worker
[1133] undefined method `l' for class RepositoryGitExtra
[1133] /home/reduser/.gems/ruby/3.3.0/gems/activerecord-7.1.3/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
    /home/reduser/redmine/plugins/redmine_git_hosting/app/models/repository_git_extra.rb:6:in `<class:RepositoryGitExtra>'
    /home/reduser/redmine/plugins/redmine_git_hosting/app/models/repository_git_extra.rb:3:in `<top (required)>'
    /usr/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
    /usr/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
    /home/reduser/.gems/ruby/3.3.0/gems/zeitwerk-2.6.13/lib/zeitwerk/kernel.rb:26:in `require'
    /home/reduser/.gems/ruby/3.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
    /home/reduser/.gems/ruby/3.3.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/helpers.rb:135:in `const_get'
    /home/reduser/.gems/ruby/3.3.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/helpers.rb:135:in `cget'
    /home/reduser/.gems/ruby/3.3.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/eager_load.rb:175:in `block in actual_eager_load_dir'
    /home/reduser/.gems/ruby/3.3.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/helpers.rb:40:in `block in ls'
    /home/reduser/.gems/ruby/3.3.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/helpers.rb:25:in `each'
    /home/reduser/.gems/ruby/3.3.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/helpers.rb:25:in `ls'
    /home/reduser/.gems/ruby/3.3.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/eager_load.rb:170:in `actual_eager_load_dir'
    /home/reduser/.gems/ruby/3.3.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/eager_load.rb:17:in `block (2 levels) in eager_load'
    /home/reduser/.gems/ruby/3.3.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/eager_load.rb:16:in `each'
    /home/reduser/.gems/ruby/3.3.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/eager_load.rb:16:in `block in eager_load'
    /home/reduser/.gems/ruby/3.3.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/eager_load.rb:10:in `synchronize'
    /home/reduser/.gems/ruby/3.3.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/eager_load.rb:10:in `eager_load'
    /home/reduser/.gems/ruby/3.3.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader.rb:379:in `block in eager_load_all'
    /home/reduser/.gems/ruby/3.3.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader.rb:377:in `each'
    /home/reduser/.gems/ruby/3.3.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader.rb:377:in `eager_load_all'
    /home/reduser/.gems/ruby/3.3.0/gems/railties-7.1.3/lib/rails/application/finisher.rb:80:in `block in <module:Finisher>'
    /home/reduser/.gems/ruby/3.3.0/gems/railties-7.1.3/lib/rails/initializable.rb:32:in `instance_exec'
    /home/reduser/.gems/ruby/3.3.0/gems/railties-7.1.3/lib/rails/initializable.rb:32:in `run'
    /home/reduser/.gems/ruby/3.3.0/gems/railties-7.1.3/lib/rails/initializable.rb:61:in `block in run_initializers'
    /usr/lib/ruby/3.3.0/tsort.rb:231:in `block in tsort_each'
    /usr/lib/ruby/3.3.0/tsort.rb:353:in `block (2 levels) in each_strongly_connected_component'
    /usr/lib/ruby/3.3.0/tsort.rb:434:in `each_strongly_connected_component_from'
    /usr/lib/ruby/3.3.0/tsort.rb:352:in `block in each_strongly_connected_component'
    /usr/lib/ruby/3.3.0/tsort.rb:350:in `each'
    /usr/lib/ruby/3.3.0/tsort.rb:350:in `call'
    /usr/lib/ruby/3.3.0/tsort.rb:350:in `each_strongly_connected_component'
    /usr/lib/ruby/3.3.0/tsort.rb:229:in `tsort_each'
    /usr/lib/ruby/3.3.0/tsort.rb:208:in `tsort_each'
    /home/reduser/.gems/ruby/3.3.0/gems/railties-7.1.3/lib/rails/initializable.rb:60:in `run_initializers'
    /home/reduser/.gems/ruby/3.3.0/gems/railties-7.1.3/lib/rails/application.rb:426:in `initialize!'
    /home/reduser/redmine/config/environment.rb:16:in `<top (required)>'
    config.ru:3:in `require_relative'
    config.ru:3:in `block in <main>'
    /home/reduser/.gems/ruby/3.3.0/gems/rack-3.0.9.1/lib/rack/builder.rb:103:in `eval'
    /home/reduser/.gems/ruby/3.3.0/gems/rack-3.0.9.1/lib/rack/builder.rb:103:in `new_from_string'
    /home/reduser/.gems/ruby/3.3.0/gems/rack-3.0.9.1/lib/rack/builder.rb:94:in `load_file'
    /home/reduser/.gems/ruby/3.3.0/gems/rack-3.0.9.1/lib/rack/builder.rb:64:in `parse_file'
    /home/reduser/.gems/ruby/3.3.0/gems/puma-6.4.2/lib/puma/configuration.rb:368:in `load_rackup'
    /home/reduser/.gems/ruby/3.3.0/gems/puma-6.4.2/lib/puma/configuration.rb:290:in `app'
    /home/reduser/.gems/ruby/3.3.0/gems/puma-6.4.2/lib/puma/runner.rb:173:in `app'
    /home/reduser/.gems/ruby/3.3.0/gems/puma-6.4.2/lib/puma/runner.rb:177:in `start_server'
    /home/reduser/.gems/ruby/3.3.0/gems/puma-6.4.2/lib/puma/cluster/worker.rb:60:in `run'
    /home/reduser/.gems/ruby/3.3.0/gems/puma-6.4.2/lib/puma/cluster.rb:216:in `worker'
    /home/reduser/.gems/ruby/3.3.0/gems/puma-6.4.2/lib/puma/cluster.rb:97:in `block in spawn_worker'
    /home/reduser/.gems/ruby/3.3.0/gems/puma-6.4.2/lib/puma/cluster.rb:97:in `fork'
    /home/reduser/.gems/ruby/3.3.0/gems/puma-6.4.2/lib/puma/cluster.rb:97:in `spawn_worker'
    /home/reduser/.gems/ruby/3.3.0/gems/puma-6.4.2/lib/puma/cluster.rb:81:in `block in spawn_workers'
    <internal:numeric>:237:in `times'
    /home/reduser/.gems/ruby/3.3.0/gems/puma-6.4.2/lib/puma/cluster.rb:74:in `spawn_workers'
    /home/reduser/.gems/ruby/3.3.0/gems/puma-6.4.2/lib/puma/cluster.rb:430:in `run'
    /home/reduser/.gems/ruby/3.3.0/gems/puma-6.4.2/lib/puma/launcher.rb:194:in `run'
    /home/reduser/.gems/ruby/3.3.0/gems/puma-6.4.2/lib/puma/cli.rb:75:in `run'
    /home/reduser/.gems/ruby/3.3.0/gems/puma-6.4.2/bin/puma:10:in `<top (required)>'
    /home/reduser/.gems/ruby/3.3.0/bin/puma:25:in `load'
    /home/reduser/.gems/ruby/3.3.0/bin/puma:25:in `<top (required)>'
    /usr/lib/ruby/gems/3.3.0/gems/bundler-2.5.3/lib/bundler/cli/exec.rb:58:in `load'
    /usr/lib/ruby/gems/3.3.0/gems/bundler-2.5.3/lib/bundler/cli/exec.rb:58:in `kernel_load'
    /usr/lib/ruby/gems/3.3.0/gems/bundler-2.5.3/lib/bundler/cli/exec.rb:23:in `run'
    /usr/lib/ruby/gems/3.3.0/gems/bundler-2.5.3/lib/bundler/cli.rb:453:in `exec'
    /usr/lib/ruby/gems/3.3.0/gems/bundler-2.5.3/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
    /usr/lib/ruby/gems/3.3.0/gems/bundler-2.5.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
    /usr/lib/ruby/gems/3.3.0/gems/bundler-2.5.3/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
    /usr/lib/ruby/gems/3.3.0/gems/bundler-2.5.3/lib/bundler/cli.rb:34:in `dispatch'
    /usr/lib/ruby/gems/3.3.0/gems/bundler-2.5.3/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
    /usr/lib/ruby/gems/3.3.0/gems/bundler-2.5.3/lib/bundler/cli.rb:28:in `start'
    /usr/lib/ruby/gems/3.3.0/gems/bundler-2.5.3/exe/bundle:28:in `block in <top (required)>'
    /usr/lib/ruby/gems/3.3.0/gems/bundler-2.5.3/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
    /usr/lib/ruby/gems/3.3.0/gems/bundler-2.5.3/exe/bundle:20:in `<top (required)>'
    /usr/bin/bundle:25:in `load'
    /usr/bin/bundle:25:in `<main>'
[1133] Early termination of worker

```

**Comment by HighwayStar** [comment]
this could be fixed by #836
