### ISSUE TITLE
ArgumentError in call_webservices.rb: Incorrect argument passing to http_post method causes failure

### ISSUE THREAD

**Issue by pavelsky75** [redmine-git-hosting/redmine_git_hosting#834]
https://github.com/redmine-git-hosting/redmine_git_hosting/blob/746493ca767e03ad860a3af85faaee8f96364678/app/services/redmine_hooks/call_webservices.rb#L110

Hello,

I've encountered an ArgumentError when using the redmine_git_hosting plugin, specifically related to the http_post method invocation in call_webservices.rb.

Error Message:

> ArgumentError (wrong number of arguments (given 2, expected 1)):
> plugins/redmine_git_hosting/app/services/redmine_hooks/http_helper.rb:9:in `http_post'

Problem Details:

In the file call_webservices.rb, the method http_post is called with two positional arguments:

`post_failed, post_message = send(use_method, post_receive_url.url, { data: { payload: payload } })
`
However, the http_post method in http_helper.rb is defined to accept one positional argument and keyword arguments:

```
def http_post(url, **opts)
  RedmineGitHosting::Utils::Http.http_post url, **opts
end
```

Passing the data hash as a second positional argument leads to an ArgumentError in Ruby 2.7 and newer versions, due to changes in how keyword arguments are handled.

Cause:

    Method Definition:
        http_post expects one positional argument (url) and any number of keyword arguments (**opts).
    Method Invocation:
        The method is invoked with two positional arguments, the second being a hash intended as keyword arguments.

Proposed Solution:

Modify the method call in call_webservices.rb to pass the data hash as keyword arguments:

`post_failed, post_message = send(use_method, post_receive_url.url, data: { payload: payload })
`
This change aligns with the method definition and resolves the ArgumentError.

**Comment by sseide** [comment]
Same error for me - plugin triggers the update hook but its running into an exception and HTTP call is not done.
Using version 6.0.1 of redmine-git-hosting plugin.

Logfile  `git_hosting.log`
```
2025-06-03 14:47:01 +0200 [INFO] Fetching changesets for 'static-website' repository
2025-06-03 14:47:01 +0200 [INFO] Succeeded!
2025-06-03 14:47:01 +0200 [INFO] Notifying post receive urls about changes to this repository:
2025-06-03 14:47:01 +0200 [INFO] Notifying https:/my.server.ip/update-hook
```

Redmine Logfile `production.log`
```
I, [2025-06-03T14:47:01.237583 #1102]  INFO -- : [70866edf-56dc-4d66-8ee4-c4711efabecc] Started POST "/githooks/post-receive/redmine/static-website" for 10.0.0.1 at 2025-06-03 14:47:01 +0200
F, [2025-06-03T14:47:01.493339 #1102] FATAL -- : [70866edf-56dc-4d66-8ee4-c4711efabecc]   
[70866edf-56dc-4d66-8ee4-c4711efabecc] ArgumentError (wrong number of arguments (given 2, expected 1)):
[70866edf-56dc-4d66-8ee4-c4711efabecc]   
[70866edf-56dc-4d66-8ee4-c4711efabecc] plugins/redmine_git_hosting/app/services/redmine_hooks/http_helper.rb:9:in `http_get'
[70866edf-56dc-4d66-8ee4-c4711efabecc] plugins/redmine_git_hosting/app/services/redmine_hooks/call_webservices.rb:110:in `do_call_webservice'
[70866edf-56dc-4d66-8ee4-c4711efabecc] plugins/redmine_git_hosting/app/services/redmine_hooks/call_webservices.rb:105:in `call_webservice'
[70866edf-56dc-4d66-8ee4-c4711efabecc] plugins/redmine_git_hosting/app/services/redmine_hooks/call_webservices.rb:19:in `block in call'
[70866edf-56dc-4d66-8ee4-c4711efabecc] plugins/redmine_git_hosting/app/services/redmine_hooks/base.rb:52:in `execute_hook'
[70866edf-56dc-4d66-8ee4-c4711efabecc] plugins/redmine_git_hosting/app/services/redmine_hooks/call_webservices.rb:17:in `call'
[70866edf-56dc-4d66-8ee4-c4711efabecc] plugins/redmine_git_hosting/app/services/redmine_hooks/base.rb:14:in `call'
[70866edf-56dc-4d66-8ee4-c4711efabecc] plugins/redmine_git_hosting/app/use_cases/repositories/execute_hooks.rb:60:in `block in execute_call_webservices_hook'
[70866edf-56dc-4d66-8ee4-c4711efabecc] plugins/redmine_git_hosting/app/use_cases/repositories/execute_hooks.rb:59:in `execute_call_webservices_hook'
[70866edf-56dc-4d66-8ee4-c4711efabecc] plugins/redmine_git_hosting/app/use_cases/repositories/execute_hooks.rb:20:in `call'
[70866edf-56dc-4d66-8ee4-c4711efabecc] plugins/redmine_git_hosting/app/use_cases/repositories/execute_hooks.rb:15:in `call'
[70866edf-56dc-4d66-8ee4-c4711efabecc] plugins/redmine_git_hosting/lib/hrack/server.rb:43:in `block in post_receive_redmine'
```
